language: go
go:
  - 1.8

sudo: false

# we only need a single git commit
git:
  depth: 1

before_install:
- sudo apt-get update
- sudo apt-get install python3.5

# test-and-build does the installation, so tell travis to skip the
# installation step
install: true

script:
  - ./scripts/test-and-build.sh
