language: go
go:
  - 1.8

sudo: required

# we only need a single git commit
git:
  depth: 1

install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-dev

script:
  - ./scripts/test-and-build.sh
