[ tool.giles ]

  [ tool.giles.circleci_artifacts.docs ]
    url = "gen/index.html"
    message = "Click details to preview the HTML documentation."

  [ tool.giles.circleci_artifacts.random ]
    url = "client-server/index.html"
    message = "Click to preview the swagger build."
