gendoc: &gendoc
  name: Generate the docs
  command: |
    source /env/bin/activate
    scripts/gendoc.py

version: 2
jobs:
  build-docs:
    docker:
      - image: uhoreg/matrix-doc-build
    steps:
      - checkout
      - run: *gendoc
      - store_artifacts:
          path: scripts/gen
      - run:
          name: "Doc build is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/scripts/gen/index.html"; echo $DOCS_URL

workflows:
  version: 2

  egg-info:
    jobs:
      - build-docs

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
