gendoc: &gendoc
  name: Generate the docs
  command: |
    source /env/bin/activate
    scripts/gendoc.py

version: 2
jobs:
  build-docs:
    docker:
      - image: uhoreg/matrix-doc-build
    steps:
      - checkout
      - run: *gendoc

workflows:
  version: 2

  egg-info:
    jobs:
      - build-docs

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
