version: 2
jobs:
  build-docs:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install -r scripts/requirements.txt
      - run: python scripts/gendoc.py

workflows:
  version: 2

  egg-info:
    jobs:
      - build-docs

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
