# Copyright 2016 OpenMarket Ltd
# Copyright 2018 New Vector Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
swagger: '2.0'
info:
  title: "Matrix Application Service API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: "/"
consumes:
  - application/json
produces:
  - application/json
paths:
  "/transactions/{txnId}":
    put:
      summary: Send some events to the application service.
      description: |-
        This API is called by the homeserver when it wants to push an event
        (or batch of events) to the application service.

        Note that the application service should distinguish state events
        from message events via the presence of a ``state_key``, rather than
        via the event type.
      operationId: sendTransaction
      parameters:
        - in: path
          name: txnId
          type: string
          description: |-
            The transaction ID for this set of events. Homeservers generate
            these IDs and they are used to ensure idempotency of requests.
          required: true
          x-example: "35"
        - in: body
          name: body
          description: A list of events.
          schema:
            type: object
            example: {
              "events": [
                {
                  "age": 32,
                  "content": {
                      "body": "incoming message",
                      "msgtype": "m.text"
                  },
                  "event_id": "$14328055551tzaee:localhost",
                  "origin_server_ts": 1432804485886,
                  "room_id": "!TmaZBKYIFrIPVGoUYp:localhost",
                  "type": "m.room.message",
                  "user_id": "@bob:localhost"
                },
                {
                  "age": 1984,
                  "content": {
                      "body": "another incoming message",
                      "msgtype": "m.text"
                  },
                  "event_id": "$1228055551ffsef:localhost",
                  "origin_server_ts": 1432804485886,
                  "room_id": "!TmaZBKYIFrIPVGoUYp:localhost",
                  "type": "m.room.message",
                  "user_id": "@bob:localhost"
                }
              ]
            }
            description: "Transaction informations"
            properties:
              events:
                type: array
                description: A list of events
                items:
                  type: object
                  title: Event
            required: ["events"]
      responses:
        200:
          description: The transaction was processed successfully.
          examples:
            application/json: {
            }
          schema:
            type: object