# Copyright 2018 New Vector Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  title: "Matrix Federation Events API"
  version: "1.0.0"
host: localhost:8448
schemes:
  - https
basePath: /_matrix/federation/v1
produces:
  - application/json
paths:
  "/state/{roomId}":
    get:
      summary: Get all the state of a given room
      description: |-
        Retrieves a snapshot of the entire current state of the given room.
      operationId: getRoomState
      parameters:
        - in: path
          name: roomId
          type: string
          description: The room ID to get state for.
          required: true
          x-example: "!abc123:matrix.org"
      responses:
        200:
          description: The room state for the room (kept under ``pdus``).
          schema:
            $ref: "definitions/transaction.yaml"
  "/event/{eventId}":
    get:
      summary: Get a single event
      description: |-
        Retrieves a single event.
      operationId: getEvent
      parameters:
        - in: path
          name: eventId
          type: string
          description: The event ID to get.
          required: true
          x-example: "$abc123:matrix.org"
      responses:
        200:
          description: A transaction containing a single PDU which is the event requested.
          schema:
            $ref: "definitions/transaction.yaml"
