swagger: '2.0'
info:
  title: "Matrix Client-Server v1 Room Leaving API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  accessToken:
    type: apiKey
    description: The user_id or application service access_token
    name: access_token
    in: query
paths:
  "/rooms/{roomId}/leave":
    post:
      summary: Stop the requesting user participating in a particular room.
      description: |-
        This API stops a user participating in a particular room.

        If the user was already in the room, they will no longer be able to see
        new events in the room. If the room requires an invite to join, they
        will need to be re-invited before they can re-join.

        If the user was invited to the room, but had not joined, this call
        serves to reject the invite.

        The user will still be allowed to retrieve history from the room which
        they were previously allowed to see.
      security:
        - accessToken: []
      parameters:
        - in: path
          type: string
          name: roomId
          description: The room identifier to leave.
          required: true
          x-example: "!nkl290a:matrix.org"
      responses:
        200:
          description: |-
            The room has been left.
          examples:
            application/json: |-
              {}
          schema:
            type: object
        429:
          description: This request was rate-limited.
          schema:
            "$ref": "definitions/error.yaml"
